# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# When the workflow succeeds the package will be published

name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run lint
      - run: npm test
        env:
          CI: true

  release:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: olegtarasov/get-tag@v2
      - name: Update package.json version with GIT Tag
        run: sed -i "s/0.0.0/${GIT_TAG_NAME//v}/g" $GITHUB_WORKSPACE/package.json
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
